### ISSUE TITLE
[Bug]: Server Info

### ISSUE THREAD

**Issue by SirDevEnforcement** [MiraBellierr/Kannabotto#14]
Idk if its just repl.it or something, but it "`cannot get cache`" so uhh, yeah

Also i'm borrowing some commands from the Info category, and adding a new command labelled credits, with you on it <3

((Also you and scorp would be a good couple kekw))

**Comment by MiraBellierr** [comment]
Hi @MrMando1234 , please make sure ya use the latest Discord.js version, otherwise ya need to change the code a little  
bit (refers to their docs). Other than that. please check if there is any typo in the code. It should be working fine. If the problem is still not solved, it is either Discord.js or repl.it that  making the problem.

**Comment by MiraBellierr** [comment]
Closed due to inactivity.
